// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssxqmhnpnxnwaqquswwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzeHFtaG5wbnhud2FxcXVzd3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcwNTAwNjIsImV4cCI6MjEwMjYyNjA2Mn0.ryksNcmltYLE_RYV-ptkOx4Hk14uYfPfB0KgUPRCN8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});